server:
  port: 8081

spring:
  application:
    name: task-service
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/kotlin_quest
    username: postgres
    password: postgres

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

  data:
    r2dbc:
      repositories:
        enabled: true

  springdoc:
    api-docs:
      path: /v3/api-docs
    swagger-ui:
      path: /swagger-ui.html
      enabled: true

logging:
  level:
    liquibase: DEBUG

#http://localhost:8080/swagger-ui.html
